### ISSUE TITLE
Default Applications

### ISSUE THREAD

**Issue by ubuntucinnamonremix** [ubuntucinnamonremix/ubuntucinnamon-environment#6]
Default Mail = Thunderbird
Plain Test = Pluma
Video, Music = GNOME MPV
Source Code = Pluma
Photos = gThumb

**Comment by ubuntucinnamonremix** [comment]
20.04.

**Comment by JPeisach** [comment]
Expect at LEAST Improvement/Possible part fix with ubuntucinnamon-meta issue 21.

**Comment by ubuntucinnamonremix** [comment]
This can be fixed by changing the software installed-it will eventually match and everything will be okay in the end.

-ItzSwirlz
